#pragma once

#define FLAG_TIME_FRAMEWORK

#define FLAG_VECTOR_2D_ANGLES
#define FLAG_VECTOR_2D_VECTOR_MATH
#define FLAG_VECTOR_2D_DISTANCES
#define FLAG_VECTOR_2D_INTERPOLATION
#define FLAG_VECTOR_2D_PID_CALCULATION

#define FLAG_ROBOT_BASE

#ifdef FLAG_TIME_FRAMEWORK

#define FLAG_INCLUSION_TIME_FRAMEWORK

#endif // FLAG_TIME_FRAMEWORK

#ifdef FLAG_VECTOR_2D_VECTOR_MATH

#define VECTOR_2D_ENABLE_VECTOR_MATH

#endif // FLAG_VECTOR_2D_VECTOR_MATH

#ifdef FLAG_VECTOR_2D_DISTANCES

#define VECTOR_2D_ENABLE_DISTANCES

#endif

#ifdef FLAG_VECTOR_2D_INTERPOLATION

#define VECTOR_2D_ENABLE_INTERPOLATION

#endif

#ifdef FLAG_VECTOR_2D_PID_CALCULATION

#define VECTOR_2D_ENABLE_PID_CALCULATION

#endif

#ifdef FLAG_VECTOR_2D_ANGLES

#define VECTOR_2D_ENABLE_ANGLES

#endif // FLAG_VECTOR_2D_ANGLES

#ifdef FLAG_ROBOT_BASE

#define FLAG_INCLUSION_ROBOT_BASE

#endif // DEBUG



